### ISSUE TITLE
[Epic] Create all required endpoint routes

### ISSUE THREAD

**Issue by SherRao** [KonferCA/SPUR-Onboard#166]
## Checklist
Before submitting this epic, make sure this epic:
- [x] Is **labelled properly** - make sure to add labels for each part of the project this epic will touch.
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.
- [x] Has everyone that will work on it assigned. 

## Description
These are all the routes that will be used in the backend.

### Project Routes
- [x] #218 
- [x] #219 
- [x] #220 
- [x] #221 
- [x] #222 
- [x] #224 
- [x] #225 
- [x] #226 
- [x] #299
- [x] #300
- [x] #301
- [x] #302
- [x] #323 
- [x] #322 

### Team Member Routes
- [x] #193 
- [x] #197 
- [x] #194 
- [x] #195 
- [x] #196 

### Company Routes
- [x] #190 
- [x] #191 
- [x] #192 

### Authentication Routes
- [x] #180 
- [x] #181 
- [x] #182 
- [x] #183 
- [x] #184 
- [x] #185 
- [x] #292 

### Misc
- [x] #204 
- [x] #216 
- [x] #329

**Comment by SherRao** [comment]
This epic is finally fucking finished, moving #330 to post MVP
