### ISSUE TITLE
[Epic] Create all required middleware

### ISSUE THREAD

**Issue by SherRao** [KonferCA/SPUR-Onboard#205]
## Checklist
Before submitting this epic, make sure this epic:
- [x] Is **labelled properly** - make sure to add labels for each part of the project this epic will touch.
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.
- [x] Has everyone that will work on it assigned. 

## Description
All the middleware required for the endpoints and other parts of the backend.

## Tickets
- [x] #206 
- [x] #207
- [x] #208
- [x] #209
- [x] #210
- [x] #211
- [x] #212
- [x] #294 
- [x] #290

**Comment by SherRao** [comment]
This epic will stay open in case we need to add any bugfixes or issues related to middleware. Once we're 100% done with middleware, we can close this issue.
