### ISSUE TITLE
[Epic] Create initial Figma UI wireframes

### ISSUE THREAD

**Issue by juancwu** [KonferCA/SPUR-Onboard#3]
## Checklist
Before submitting this epic, make sure this epic:
- [x] Is **labelled properly** - make sure to add labels for each part of the project this epic will touch.
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.
- [x] Has everyone that will work on it assigned. 

## Description
These are all the wireframes required by the engineering team for the MVP.

### 1st Iteration
- [x] #16 
- [x] #19 
- [x] #89 
- [x] #199 
- [x] #265 
- [x] #266
- [x] #267 

### 2nd Iteration
- [x] #268 
- [x] #324
- [x] #325
- [x] #326
- [x] #327
- [x] #314
- [x] #328
- [x] #342
- [x] #343
- [x] #344
- [x] #384
